name: Docker
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
incremental: true
permalink: pretty
safe: false
lsi: false
url: https://docs.docker.com

gems:
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-seo-tag


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      archiveserver: "http://54.71.194.30"
  -
    scope:
      path: "datacenter/ucp/2.1"
    values:
      ucpversion: "2.1"
  - scope:
      path: "datacenter/ucp/1.0"
    values:
      ucpversion: "1.0"
